Write a function so that the columns of the output matrix are powers of the input
vector.

In [ ]:
import numpy as np

def function(in_matrix, increasing = False):
    N = len(in_matrix)
    if increasing:
        res = [[pow(i, j) for j in range(0, N)] for i in in_matrix]
        print(np.asanyarray(res))
    else:
        res = [[pow(i, j) for j in range(N-1, -1, -1) ] for i in in_matrix]
        print(np.asanyarray(res))

In [ ]:
in_matrix = [1,2,3,4]        
function(in_matrix,increasing = False)
function(in_matrix,increasing=True)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

In [ ]:
in_array=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
m=3
n=len(in_array)
output=[]
def movingaverage():
    for i in range(0,n):
        if i<n-m+1:
            sum=0
            for j in range(i,i+m):
                sum=sum+input_array[j]
            output.append(sum/m)    
    print(output)    
    
movingaverage()

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
